#!/usr/bin/python
import ml
print("minerlang v0.1")
print("(c) 2016- Robert Miles")
m = ml.minerlang()
running = True
while running:
	command = raw_input("> ")
	try:
		if command == "quit":
			running = False
		else:
			m.run(command)
	except Exception as e:
		print(e)
		continue
